### ISSUE TITLE
New Report Options

### ISSUE THREAD

**Issue by rbreslavsky** [nasa/cape#33]
In CAPE 1.1.0 or greater, some subfigure options have been disabled, such as:

- `Grid`
- `nMaxStats`
- `nStats`

Do these live somewhere else now?

**Comment by nasa-ddalle** [comment]
These were indeed missed in the re-implementation required for CAPE 1.1. I've added this (and also note `GridPlotOptions`, `MinorGrid`, and `MinorGridPlotOptions`) to both the `v1.1` and `main` branches. Note that technically I've "standardized" some of the spelling so that the official names are `NMaxStats` and `NStats`, but CAPE will rename them if you use `nStats` in the JSON file.

Here's the commits implementing this bug fix.

https://github.com/nasa/cape/commit/5403f19d063c6b892adf0cf9cb0ecc26d30d01ff
https://github.com/nasa/cape/commit/a00b6b2d32fee67743007a93e33e3181b1a9af58
