### ISSUE TITLE
Restart file missing from single-phase simulations

### ISSUE THREAD

**Issue by rbreslavsky** [nasa/cape#5]
Simulations with only one phase do not output a `run.<phase>.<iter>` file for later restarts.

**Comment by nasa-ddalle** [comment]
This should be fixed by commit `5bc9bfe` ... It appears it was caused by an error with Python 3 not letting you compare an `int` to `None`. Not 100% this will fix the problem, but was able to run a modified `pyfun02-bullet` test (https://github.com/nasa-ddalle/pyfun02-bullet) with only one phase that got the `run.00.100` file to appear.
